server:
  port: 8081

spring:
  application:
    name: rest-api

  # PostgreSQL connection
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/dms_db}
    username: ${SPRING_DATASOURCE_USERNAME:jasmin}
    password: ${SPRING_DATASOURCE_PASSWORD:swen3_dms_2901}
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect