package com.dms.rest_api.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;


/**
 * Represents a Document entity stored in the PostgreSQL database.
 * 
 * In Spring Data JPA, an @Entity class is mapped directly to a database table.
 * Each instance of this class corresponds to a single row in the 'documents' table.
 */
@Entity
@Table(name = "documents") // Defines the exact table name in the PostgreSQL database
@Data                       // Lombok: Automatically generates getters, setters, toString(), equals(), and hashCode()
@NoArgsConstructor          // Lombok: Generates a no-argument constructor (REQUIRED by JPA/Hibernate to instantiate objects)
@AllArgsConstructor         // Lombok: Generates a constructor with parameters for all fields
@Builder                    // Lombok: Enables the Builder pattern for clean and fluent object creation
public class Document {

    /**
     * Primary Key for the table.
     * 
     * @Id marks this field as the unique identifier.
     * @GeneratedValue specifies that the database automatically increments this value.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title/filename of the document.
     */
    @Column(nullable = false)
    private String title;

    /**
     * Extracted text content from the OCR process.
     * 
     * Using columnDefinition = "TEXT" maps this field to PostgreSQL's TEXT data type,
     * which allows storing large amounts of text (unlike the default VARCHAR(255)).
     */
    @Column(columnDefinition = "TEXT")
    private String content;

    /**
     * Summary generated by the Google Gemini AI Worker.
     */
    @Column(columnDefinition = "TEXT")
    private String summary;

    /**
     * Timestamp indicating when the document was uploaded.
     * 
     * @Builder.Default ensures that if created via Document.builder(),
     * the current time is automatically set as the default value.
     */
    @Builder.Default
    private LocalDateTime uploadDate = LocalDateTime.now();

    /**
     * Category to which this document belongs.
     * 
     * - @ManyToOne: Establishes a many-to-one relationship with the Category entity.
     * - FetchType.LAZY: Delays loading the category from the database until explicitly accessed.
     * - @JoinColumn: Specifies 'category_id' as the foreign key column in the 'documents' table.
     * - @JsonIgnoreProperties("documents"): Prevents infinite recursion during JSON serialization.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "documents"})
    private Category category;

}
